version: "3.8"

services:
  
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      node_cluster:
        ipv4_address: 172.18.0.10

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    depends_on: [ postgres ]
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      node_cluster:
        ipv4_address: 172.18.0.20

  app:
    image: diegomated1/database-service:${APP_VERSION}
    container_name: database-service
    restart: always
    depends_on: [ postgres, pgadmin ]
    environment:
      - port=3000
      # postgres connection
      - DATABASE=mediafile
      - USER=${PG_USER}
      - PASSWORD=${PG_PASSWORD}
      - HOST=172.18.0.10
    ports:
      - "3000:3000"
    networks:
      node_cluster:
        ipv4_address: 172.18.0.30

networks:
  node_cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1